import time
from typing import Dict, Any, List, Optional


class RecommendationCache:
    """
    In-memory cache for raw (unenriched) playlist recommendations generated by OpenAI.
    Allows paginating over large recommendation lists without re-calling the LLM.
    """

    def __init__(self, expiration_seconds: int = 1800):
        # Maps session_id -> {"songs": [...], "created_at": float}
        self._cache: Dict[str, Dict[str, Any]] = {}
        self.expiration_seconds = expiration_seconds

    def set(self, session_id: str, songs: List[Dict[str, Any]]) -> None:
        """
        Caches a list of songs under a session identifier.
        """
        self._prune()
        self._cache[session_id] = {
            "songs": songs,
            "created_at": time.time()
        }

    def get(self, session_id: str) -> Optional[List[Dict[str, Any]]]:
        """
        Retrieves a cached playlist of songs. If present, refreshes the expiration window.
        """
        self._prune()
        entry = self._cache.get(session_id)
        if entry:
            # Refresh entry lifetime on access
            entry["created_at"] = time.time()
            return entry["songs"]
        return None

    def _prune(self) -> None:
        """
        Deletes expired cache sessions to free memory.
        """
        now = time.time()
        expired = [
            sid for sid, entry in self._cache.items()
            if now - entry["created_at"] > self.expiration_seconds
        ]
        for sid in expired:
            del self._cache[sid]


# Global cache instance
recommendation_cache = RecommendationCache()
